# Generated by Django 3.2 on 2021-06-12 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('default', models.IntegerField(help_text="If a Plan hasn't set this limit, the Plan will use this default value.")),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_price', models.PositiveIntegerField(help_text='Price displayed to users for plan')),
                ('price_id', models.CharField(blank=True, help_text="Paid plans must set this and it may only be set if the Plan's type is Paid.", max_length=254, null=True, unique=True, verbose_name='Stripe Price ID.')),
                ('type', models.CharField(choices=[('free_default', 'Free (Default)'), ('free_private', 'Free (Private)'), ('paid_public', 'Paid (Public)')], default='free_default', help_text='The type of plan', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField()),
                ('info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='new', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.limit')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='limits',
            field=models.ManyToManyField(related_name='plans', through='billing.PlanLimit', to='billing.Limit'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Stripe Customer ID')),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Stripe Subscription ID')),
                ('cc_info', models.JSONField(blank=True, null=True, verbose_name='Stripe Credit Card Info')),
                ('payment_state', models.CharField(choices=[('off', 'Off'), ('ok', 'Ok'), ('error', 'Error'), ('requires_payment_method', 'Requires Payment Method'), ('requires_action', 'Requires Action')], default='off', max_length=128)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
            ],
        ),
    ]
