# Generated by Django 4.0.2 on 2022-02-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_id',
            field=models.CharField(blank=True, help_text="Paid plans must set this and it may only be set if the Plan's type is paid.", max_length=254, null=True, unique=True, verbose_name='Stripe Price ID.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('free_default', 'Free (Default)'), ('free_private', 'Free (Private)'), ('paid_public', 'Paid (Public)'), ('paid_private', 'Paid (Private)')], default='free_default', help_text='The type of plan', max_length=254),
        ),
    ]
