# Generated by Django 4.0.2 on 2022-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_price_id_alter_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='primary',
            field=models.BooleanField(default=False, help_text='Is this the primary event for the event type?'),
        ),
    ]
