# Generated by Django 3.2.8 on 2021-10-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeevent',
            name='payload',
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
