# Generated by Django 4.0.2 on 2022-04-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_stripeevent_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('current_period_end', models.DateTimeField()),
                ('price_id', models.CharField(max_length=254)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], max_length=254)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='subscription_payment_state_constraint',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='stripeevent',
            name='info',
        ),
        migrations.RemoveField(
            model_name='stripeevent',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='stripeevent',
            name='type',
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer'),
        ),
    ]
