# Generated by Django 4.0.2 on 2022-08-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_stripesubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='created',
            field=models.DateTimeField(blank=True, help_text="The timestamp of the creation of the Event on Stripe's side.", null=True),
        ),
    ]
