# Generated by Django 3.2.8 on 2021-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_stripeevent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expecting_webhook_since',
            field=models.DateTimeField(blank=True, help_text='If this is more than a minute in the past, we may have missed a Stripe webhook.', null=True),
        ),
    ]
