# Generated by Django 3.2.8 on 2021-10-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_expecting_webhook_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='payload_type',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='info',
            field=models.JSONField(blank=True, help_text='For convenience, import information from the body and other sources.', null=True),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('processed', 'Processed'), ('noop', 'Noop'), ('error', 'Error')], default='new', max_length=127),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='type',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
