# Generated by Django 3.2.8 on 2021-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20211014_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeevent',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('error', 'Error')], default='new', max_length=127),
        ),
    ]
